### ISSUE TITLE
default example failed with error

### ISSUE THREAD

**Issue by kprasadvnsi** [canonical/appstream.dart#14]
kp@kp-B550:~/trials/my_app$ dart run
Building package executable... 
Built my_app:my_app.
Unhandled exception:
FormatException: Missing component package
#0      new AppstreamCollection.fromYaml (package:appstream/src/collection.dart:421:9)
#1      AppstreamPool._loadYamlCollection (package:appstream/src/pool.dart:45:32)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#3      AppstreamPool.load (package:appstream/src/pool.dart:24:23)
<asynchronous suspension>
#4      main (file:///home/kp/trials/my_app/bin/my_app.dart:5:3)
<asynchronous suspension>

**Comment by robert-ancell** [comment]
This issue should now be fixed.

However, if you are running on Ubuntu/Debian, you may still be hitting this issue - https://github.com/ximion/appstream-generator/issues/92.

**Comment by robert-ancell** [comment]
See https://github.com/canonical/appstream.dart/issues/15
