### ISSUE TITLE
Fails to work on Ubuntu/Debian due to "Duplicate mapping key"

### ISSUE THREAD

**Issue by robert-ancell** [canonical/appstream.dart#15]
If you run the example on Ubuntu you get:
```
Unhandled exception:
Error on line 25023, column 3: Duplicate mapping key.
      ╷
25023 │   ca_ES:
      │   ^^^^^
      ╵
#0      Loader._loadMapping (package:yaml/src/loader.dart:168:9)
```

This is because appstream-generator was [generating invalid YAML](https://github.com/ximion/appstream-generator/issues/92), specifically the translation merging was leading to duplicate keys in maps (i.e. two ca_ES translations in the above example). While this is now fixed upstream, Ubuntu/Debian releases will continue to have invalid YAML files.

Possible solutions:
- We manage to update all the existing YAML in Ubuntu/Debian - however this can't fix any systems that haven't updated.
- The Dart YAML implementation slackens its requirements on maps (seems extremely unlikely/undesirable).
- We pre-process the YAML to remove these duplicates.
- We make a small YAML decoder in appstream.dart that handles this case.

**Comment by kprasadvnsi** [comment]
pre-processing the YAML might be a good solution.

**Comment by kprasadvnsi** [comment]
it doesn't seem to be fixed in upstream. I have Debian Sid with appstream 0.15 and still have this issue. 
```
Unhandled exception:
Error on line 171904, column 3: Duplicate mapping key.
       ╷
171904 │   oars-1.1: {}
       │   ^^^^^^^^
       ╵
#0      Loader._loadMapping (package:yaml/src/loader.dart:168:9)
```

**Comment by robert-ancell** [comment]
The bug is in appstream-generator, which is run on the servers to generate the appstream files. So it depends on what the Debian servers are running. Note this is different code (OARS vs translations) and might be a second bug.

**Comment by kprasadvnsi** [comment]
I guess trying to recover from these "Duplicate mapping key" expectations is the only option for now.

**Comment by robert-ancell** [comment]
I tried forking the yaml code and disabling this test and that runs fine locally, but can't be uploaded to pub.dev in that state.

**Comment by oSoMoN** [comment]
Running `yamllint` on all the compressed yaml files in `/var/lib/app-info/yaml/` on my machine running kinetic raises 3 duplicated keys in 1 file:

```bash
osomon@dantian:/var/lib/app-info/yaml$ for f in *; do echo $f; zcat -c $f > /tmp/$f; yamllint /tmp/$f | grep duplication; done
es.archive.ubuntu.com_ubuntu_dists_kinetic_main_dep11_Components-amd64.yml.gz
es.archive.ubuntu.com_ubuntu_dists_kinetic_multiverse_dep11_Components-amd64.yml.gz
es.archive.ubuntu.com_ubuntu_dists_kinetic_universe_dep11_Components-amd64.yml.gz
  170229:3  error    duplication of key "oars-1.1" in mapping  (key-duplicates)
  326444:3  error    duplication of key "oars-1.1" in mapping  (key-duplicates)
  401603:3  error    duplication of key "ca_ES" in mapping  (key-duplicates)
es.archive.ubuntu.com_ubuntu_dists_kinetic-updates_main_dep11_Components-amd64.yml.gz
es.archive.ubuntu.com_ubuntu_dists_kinetic-updates_universe_dep11_Components-amd64.yml.gz
security.ubuntu.com_ubuntu_dists_kinetic-security_main_dep11_Components-amd64.yml.gz
security.ubuntu.com_ubuntu_dists_kinetic-security_universe_dep11_Components-amd64.yml.gz
```

I've had a look at the problem, and it seems to me the most sensible approach is option #3 ("We pre-process the YAML to remove these duplicates").
